# Generated by Django 4.0 on 2023-03-25 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timest', models.TimeField()),
                ('Msg', models.TextField(max_length=1000)),
                ('ToUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toUser', to='auth.user')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sendUser', to='auth.user')),
            ],
        ),
    ]
